import "./globals.css"
import type { Metadata } from "next"
import { Kanit } from "next/font/google"
import { Providers } from "@/redux/provider"

const inter = Kanit({ subsets: ["thai"], weight: "400" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
